[macro_parameters]
batch_size = 64
epochs = 5

[model]
name = "squeezenet_1_0"
end = 1
classifier = "../json_modules/alexnet_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.001

[loss_function]
name = "CrossEntropyLoss"